
# Install and setup composer
- name: Install PHP Composer
  script: files/composer/install_composer.sh

- name: Make Composer available for future tasks...
  command: mv composer.phar /usr/local/bin/composer
  become: true

- name: Set permissions on global composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
  become: true

- name: Install dependencies
  composer:
    command: install
    working_dir: "{{synchweb_home}}/api"

#
# Patch src files as required
#
- name: Copy patched CAS authentication across full ssl working...
  copy: src=files/SynchWeb/CAS.php dest="{{ synchweb_home }}/api/src/Authentication/Type/CAS.php" owner=vagrant group=vagrant mode=0644

- name: Copy patched UAS file across (would need to be swapped for UAS)
  copy: src=files/SynchWeb/MockUAS.php dest="{{ synchweb_home }}/api/src/MockUAS.php" owner=vagrant group=vagrant mode=0644

# Finally set the ownership to vagrant.
- name: Change ownership to vagrant
  file:
      path: "{{ synchweb_home }}/api/vendor"
      owner: vagrant
      group: vagrant
      recurse: yes

## Fixes...
- name: Ensure mpdf writable cache
  file:
    path: "{{ synchweb_home }}/api/vendor/mpdf/mpdf/ttfontdata"
    state: directory
    group: vagrant
    mode: o+w

- name: Ensure HTMLPurifier writable cache
  file:
    path: "{{ synchweb_home }}/api/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/HTML"
    state: directory
    group: vagrant
    mode: o+w
