- include_tasks: centos/install_packages.centos.yml
  when: ansible_distribution == "CentOS"

- include_tasks: debian/install_packages.debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

# Tasks that Download/Checkout SynchWeb repository
- include_tasks: synchweb_development.yml

# Setup Apache based on OS
- include_tasks: centos/setup_apache.centos.yml
  when: ansible_distribution == "CentOS"

- include_tasks: debian/setup_apache.debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: copy hosts file to server
  copy:
    src: files/system/etc/hosts
    dest: /etc/hosts

 