---
# Changes to build npm
- name: Get the nodejs package repo
  get_url:
    url: https://rpm.nodesource.com/setup_10.x
    dest: /tmp/setup_nodejs

- name: Install nodejs package repo
  command: sh setup_nodejs
  args:
    chdir: /tmp
  become: true

- name: Install npm
  package:
    name: nodejs
    state: latest

- name: Install webpack dependencies
  npm:
    path: "{{synchweb_home}}/client"
  become: yes
  become_user: vagrant

- name: Build client
  command: "npm run build:dev"
  args:
    chdir: "{{synchweb_home}}/client"
  become: yes
  become_user: vagrant

# If there is a client/index.html, copy this to the index.php file
# Once apache config is updated to also read an index.html file we can remove this step
- name: Replace index.php with an index.html file
  command: "cp index.html index.php"
  args:
    chdir: "{{synchweb_home}}/client"
  ignore_errors: yes
