---
# Install MySQL (MariaDB) packages
  - name: Add MariaDB repository
    yum_repository:
      name: mariadb
      description: MariaDB
      baseurl: http://yum.mariadb.org/10.3/centos7-amd64
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes

  - name: Install MySQL Python for remote configuration
    yum: name=MySQL-python state=present

  - name: Install MariaDB Server
    yum: name=MariaDB-server state=present

  - name: Install MariaDB Client
    yum: name=MariaDB-client state=present

  - name: Start the MariaDB service
    service:
      name: mariadb
      state: started
      enabled: yes
