apiVersion: v1
kind: Service
metadata:
  name: synchweb
  labels:
    app: synchweb
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: synchweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synchweb
spec:
  selector:
    matchLabels:
      app: synchweb
  replicas: 1
  template:
    metadata:
      labels:
        app: synchweb
    spec:
      volumes:
       - name: dls
         hostPath:
           path: /dls
       - name: synchweb-cert
         secret:
           secretName: synchweb-cert
       - name: synchweb-key
         secret:
           secretName: synchweb-key
      containers:
       - name: synchweb
         image: gcr.io/diamond-privreg/path/to/image/here:latest
         command: ["/app/entrypoint.bash"]
         volumeMounts:
          - mountPath: /dls
            name: dls
            mountPropagation: HostToContainer
          - mountPath: /etc/pki/tls/certs/synchweb
            name: synchweb-cert
            readOnly: true
          - mountPath: /etc/pki/tls/private/synchweb
            name: synchweb-key
            readOnly: true
