# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#
# For shared folders use geerlingguy/centos7 instead of centos/7
Vagrant.configure("2") do |config|
  #config.vm.box = "geerlingguy/centos7"
  config.vm.box = "centos/7"

  # If we are using CAS we should provision it first
  # Then we can copy the certificates across to SynchWeb host
  config.vm.define "cas" do |cas|
    cas.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
    cas.vm.network "private_network", ip: "192.168.33.12"
    cas.vm.hostname="cas.example.org"
    cas.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbooks/cas.yml"
    end
  end

  config.vm.define "synchweb" do |synchweb|
    # Either use private network or expose ports on localhost
    synchweb.vm.network "private_network", ip: "192.168.33.10"
    synchweb.vm.hostname="synchweb.example.org"

    # Synched folder does not play nicely with webpack node-sass package
    # synchweb.vm.synced_folder "src/", "/var/www/sites/"

    # Comment out next two definitions if on Windows
    synchweb.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbooks/synchweb.yml"
    end
  end

end
